//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiTietTrongNgay
    {
        public string MaKhuVuc { get; set; }
        public System.DateTime Gio { get; set; }
        public Nullable<decimal> NhietDo { get; set; }
        public Nullable<decimal> DoAm { get; set; }
    }
}
